export const mockUserProfile = {
  nickname: "Mia",
  goal: "均衡饮食",
  streakDays: 18,
  taste: "清淡、鲜香、少油",
  avoid: "花生、过甜饮品、深夜高脂餐",
  budget: "每日 80 元以内",
  cookingTime: "30 分钟内",
};

export const mockNutritionReport = {
  calories: { value: 1680, target: 1900, unit: "kcal" },
  protein: { value: 92, target: 105, unit: "g" },
  carbs: { value: 188, target: 220, unit: "g" },
  fat: { value: 49, target: 60, unit: "g" },
  water: { value: 6, target: 8, unit: "cups" },
  weekly: {
    averageCalories: "1820 kcal",
    proteinRate: "87%",
    vegetableFrequency: "5 天",
    score: 86,
  },
  suggestions: [
    "本周蛋白质摄入较稳定，适合继续保持。",
    "建议增加深色蔬菜，例如菠菜、羽衣甘蓝或西兰花。",
    "建议减少高糖零食，把下午茶换成酸奶或坚果。",
  ],
};

export const mockMeals = [
  {
    type: "早餐",
    name: "希腊酸奶燕麦碗",
    calories: 360,
    protein: 24,
    carbs: 48,
    fat: 8,
    time: "8 min",
    reason: "高蛋白、低负担，适合工作日前半天保持饱腹感。",
    tag: "高蛋白",
  },
  {
    type: "午餐",
    name: "三文鱼菠菜糙米碗",
    calories: 540,
    protein: 38,
    carbs: 58,
    fat: 18,
    time: "22 min",
    reason: "优先使用冰箱里的菠菜，同时补充优质脂肪。",
    tag: "均衡",
  },
  {
    type: "晚餐",
    name: "番茄豆腐蔬菜汤",
    calories: 420,
    protein: 28,
    carbs: 42,
    fat: 12,
    time: "25 min",
    reason: "晚餐更轻盈，控制总热量并补足蔬菜。",
    tag: "轻食",
  },
  {
    type: "加餐",
    name: "蓝莓坚果酸奶杯",
    calories: 180,
    protein: 11,
    carbs: 18,
    fat: 7,
    time: "5 min",
    reason: "替代高糖零食，稳定下午能量。",
    tag: "低糖",
  },
];

export const mockRecipes = [
  {
    id: "r-salmon-bowl",
    name: "三文鱼菠菜糙米碗",
    category: "午餐",
    calories: 540,
    protein: 38,
    carbs: 58,
    fat: 18,
    time: "22 min",
    difficulty: "简单",
    tags: ["高蛋白", "均衡", "快手菜"],
    gradient: "from-emerald-100 via-lime-50 to-amber-100",
    imageLabel: "Salmon Bowl",
    reason: "适合减脂和均衡饮食，优先消耗菠菜。",
    ingredients: [
      { name: "三文鱼", amount: "160g", inPantry: true },
      { name: "菠菜", amount: "120g", inPantry: true },
      { name: "糙米饭", amount: "150g", inPantry: true },
      { name: "柠檬", amount: "1/2 个", inPantry: false },
    ],
    steps: [
      "三文鱼用盐、黑胡椒和柠檬汁腌制 8 分钟。",
      "平底锅少油煎至两面金黄。",
      "菠菜快速翻炒，和糙米饭一起装碗。",
      "加入酸奶香草酱，搭配柠檬片食用。",
    ],
    aiTip: "如果今天运动量较低，可以把糙米饭减到 100g。",
  },
  {
    id: "r-yogurt-oats",
    name: "希腊酸奶燕麦碗",
    category: "早餐",
    calories: 360,
    protein: 24,
    carbs: 48,
    fat: 8,
    time: "8 min",
    difficulty: "简单",
    tags: ["早餐", "高蛋白", "低卡"],
    gradient: "from-sky-100 via-white to-emerald-100",
    imageLabel: "Yogurt Oats",
    reason: "高蛋白早餐，适合忙碌早晨。",
    ingredients: [
      { name: "希腊酸奶", amount: "200g", inPantry: true },
      { name: "燕麦", amount: "45g", inPantry: true },
      { name: "蓝莓", amount: "60g", inPantry: false },
      { name: "奇亚籽", amount: "8g", inPantry: true },
    ],
    steps: ["酸奶倒入碗中。", "加入燕麦和奇亚籽。", "铺上蓝莓，冷藏 5 分钟后食用。"],
    aiTip: "如果上午会议较多，可以额外加半根香蕉提升饱腹感。",
  },
  {
    id: "r-tofu-soup",
    name: "番茄豆腐蔬菜汤",
    category: "晚餐",
    calories: 420,
    protein: 28,
    carbs: 42,
    fat: 12,
    time: "25 min",
    difficulty: "简单",
    tags: ["晚餐", "低卡", "轻食"],
    gradient: "from-rose-100 via-orange-50 to-lime-100",
    imageLabel: "Tofu Soup",
    reason: "晚餐轻负担，适合控糖和减脂。",
    ingredients: [
      { name: "番茄", amount: "2 个", inPantry: true },
      { name: "北豆腐", amount: "180g", inPantry: false },
      { name: "鸡蛋", amount: "1 个", inPantry: true },
      { name: "青菜", amount: "100g", inPantry: true },
    ],
    steps: ["番茄炒出汁。", "加入清水和豆腐煮 10 分钟。", "淋入蛋液，最后加入青菜。"],
    aiTip: "番茄和鸡蛋快到期，建议今天优先使用。",
  },
  {
    id: "r-chicken-wrap",
    name: "鸡胸牛油果全麦卷",
    category: "午餐",
    calories: 510,
    protein: 41,
    carbs: 46,
    fat: 17,
    time: "18 min",
    difficulty: "中等",
    tags: ["午餐", "高蛋白", "快手菜"],
    gradient: "from-lime-100 via-green-50 to-stone-100",
    imageLabel: "Chicken Wrap",
    reason: "适合外带，蛋白质和脂肪比例稳定。",
    ingredients: [
      { name: "鸡胸肉", amount: "150g", inPantry: true },
      { name: "全麦饼", amount: "1 张", inPantry: false },
      { name: "牛油果", amount: "1/2 个", inPantry: false },
      { name: "生菜", amount: "80g", inPantry: true },
    ],
    steps: ["鸡胸肉煎熟切片。", "全麦饼加热。", "铺上生菜、鸡胸肉和牛油果后卷紧。"],
    aiTip: "预算有限时，可用鸡蛋替代牛油果。",
  },
  {
    id: "r-shrimp-noodles",
    name: "虾仁荞麦面",
    category: "晚餐",
    calories: 480,
    protein: 34,
    carbs: 62,
    fat: 10,
    time: "20 min",
    difficulty: "简单",
    tags: ["晚餐", "低脂", "快手菜"],
    gradient: "from-cyan-100 via-white to-emerald-100",
    imageLabel: "Soba",
    reason: "低脂高蛋白，适合训练后晚餐。",
    ingredients: [
      { name: "虾仁", amount: "140g", inPantry: false },
      { name: "荞麦面", amount: "80g", inPantry: true },
      { name: "黄瓜", amount: "1 根", inPantry: true },
      { name: "低钠酱油", amount: "1 勺", inPantry: true },
    ],
    steps: ["荞麦面煮熟过冷水。", "虾仁焯熟。", "加入黄瓜丝和低钠酱汁拌匀。"],
    aiTip: "控糖用户可减少面量，增加黄瓜和海带芽。",
  },
  {
    id: "r-egg-toast",
    name: "鸡蛋牛油果吐司",
    category: "早餐",
    calories: 390,
    protein: 22,
    carbs: 36,
    fat: 18,
    time: "12 min",
    difficulty: "简单",
    tags: ["早餐", "均衡", "快手菜"],
    gradient: "from-amber-100 via-white to-green-100",
    imageLabel: "Egg Toast",
    reason: "快速补充蛋白质和健康脂肪。",
    ingredients: [
      { name: "鸡蛋", amount: "2 个", inPantry: true },
      { name: "全麦吐司", amount: "2 片", inPantry: true },
      { name: "牛油果", amount: "1/2 个", inPantry: false },
    ],
    steps: ["鸡蛋煎至半熟。", "吐司烤脆。", "抹上牛油果泥并放上鸡蛋。"],
    aiTip: "如果今天脂肪摄入偏高，可把牛油果减半。",
  },
];

export const mockPantryItems = [
  { id: "p1", name: "菠菜", category: "蔬菜", quantity: "280g", expiresIn: "2 天", status: "即将过期", use: "三文鱼菠菜糙米碗" },
  { id: "p2", name: "鸡蛋", category: "肉蛋奶", quantity: "3 个", expiresIn: "4 天", status: "库存不足", use: "番茄豆腐蔬菜汤" },
  { id: "p3", name: "糙米", category: "主食", quantity: "1.2kg", expiresIn: "30 天", status: "正常", use: "能量主食" },
  { id: "p4", name: "番茄", category: "蔬菜", quantity: "2 个", expiresIn: "1 天", status: "即将过期", use: "番茄豆腐蔬菜汤" },
  { id: "p5", name: "希腊酸奶", category: "肉蛋奶", quantity: "2 杯", expiresIn: "3 天", status: "正常", use: "早餐燕麦碗" },
  { id: "p6", name: "苹果", category: "水果", quantity: "4 个", expiresIn: "7 天", status: "正常", use: "下午加餐" },
  { id: "p7", name: "低钠酱油", category: "调味品", quantity: "1 瓶", expiresIn: "90 天", status: "正常", use: "低盐调味" },
];

export const mockShoppingList = [
  {
    group: "蔬菜水果",
    items: [
      { id: "s1", name: "蓝莓", amount: "250g", price: "18 元", checked: false },
      { id: "s2", name: "牛油果", amount: "2 个", price: "24 元", checked: false },
      { id: "s3", name: "柠檬", amount: "2 个", price: "8 元", checked: true },
    ],
  },
  {
    group: "肉蛋奶",
    items: [
      { id: "s4", name: "北豆腐", amount: "2 盒", price: "12 元", checked: false },
      { id: "s5", name: "虾仁", amount: "300g", price: "36 元", checked: false },
    ],
  },
  {
    group: "主食谷物",
    items: [
      { id: "s6", name: "全麦饼", amount: "1 包", price: "16 元", checked: false },
      { id: "s7", name: "燕麦", amount: "500g", price: "19 元", checked: true },
    ],
  },
  {
    group: "调味品",
    items: [
      { id: "s8", name: "无糖酸奶酱", amount: "1 瓶", price: "15 元", checked: false },
    ],
  },
];

export const mockAiPlan = {
  analysis: ["正在分析饮食目标", "正在匹配现有食材", "正在计算营养比例", "正在生成一周餐单"],
  today: ["早餐：希腊酸奶燕麦碗", "午餐：三文鱼菠菜糙米碗", "晚餐：番茄豆腐蔬菜汤"],
  weeklySummary: ["周一到周三优先使用菠菜、番茄和鸡蛋", "训练日提高蛋白质比例", "晚餐保持轻食，减少高糖加餐"],
  score: 86,
  groceries: ["蓝莓", "北豆腐", "牛油果", "柠檬"],
  reason: "当前计划优先使用即将过期的菠菜和番茄，同时把每日预算控制在 80 元以内。",
};
